---
title: "LM and GLM 210519"
author: "Peter Yates"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning =F)
```

```{r, include=F}
#Load packages
lapply(c("R.matlab","knitr","RODBC","MASS", 
         "tweedie", "nlme", "statmod","mgcv", 
         "raster", "lattice", "ggplot2",
         "fields","rgdal", "plyr","dplyr",
         "gdata", "gstat","car","visreg","tidyr",
         "plotrix","hexbin", "R.matlab", "ggmap","viridis",
         "weathermetrics", "chron", "RColorBrewer","lattice",
         "ncdf4", "geosphere", "maptools", "sp", "oce", "pracma",
         "gridExtra", "maps", "mapdata", "sp", "rgeos", "lubridate"), require, character.only = TRUE)
#Source Highland Statistics code
source("2code/HighstatLibV6.R")

#read data
df	<- read.csv("1data/CleanedData_060519.csv", header=TRUE, sep=",", dec=".", fill=TRUE)
```

```{r, fig.height = 8, fig.width =10}
#filter the data
df2 <- df[df$site!="CB",]

#make df_E
df_E <- df2[!is.na(df2$fluorescence), ] 
df_E2 <- df_E[!is.na(df_E$Nitrate), ]
```

## LM with transformations
```{r, fig.height = 8, fig.width =10}
M1<- lm(Biomass~Temp+log10(fluorescence)+log10(GA_depth2)+Dbin+site2+Nitrate,
         data=df2)
E1 <- resid(M1, type = "pearson")
summary(M1)
par(mfrow=c(2,2))
plot(M1)
df_E2$E1 <- E1
MyVar <- c("Temp", "fluorescence", "GA_depth2", "Lon", "Nitrate")
MyxyplotPolygon(df_E2, MyVar, "E1")
```

### Fitted relationships M1

```{r, fig.height = 8, fig.width =10}
par(mfrow=c(2,3))
visreg(M1, "fluorescence")
visreg(M1, "Temp")
visreg(M1, "GA_depth2")
visreg(M1, "site2")
visreg(M1, "Dbin")
visreg(M1, "Nitrate")
```

## GLM with transformations
```{r, fig.height = 8, fig.width =10}
M2<- glm(Biomass~Temp+log10(fluorescence)+log10(GA_depth2)+Dbin+site2+Nitrate,
         data=df2,family=Gamma(link="log"))
E2 <- resid(M2, type = "pearson")
summary(M2)
par(mfrow=c(2,2))
plot(M2)
 
df_E2$E2 <- E2
MyVar <- c("Temp", "fluorescence", "GA_depth2", "Lon", "Nitrate")
MyxyplotPolygon(df_E2, MyVar, "E2")
```

### Fitted relationships M2

```{r, fig.height = 8, fig.width =10}
par(mfrow=c(2,3))
visreg(M2, "fluorescence")
visreg(M2, "Temp")
visreg(M2, "GA_depth2")
visreg(M2, "site2")
visreg(M2, "Dbin")
visreg(M2, "Nitrate")
```


